export const categories = [
  { title: "All", category: "All" },
  { title: "Houses", category: "House" },
  { title: "Condos", category: "Condos" },
  { title: "Duplexes", category: "Duplexes" },
  { title: "Studios", category: "Studios" },
  { title: "Villas", category: "Villa" },
  { title: "Apartments", category: "Apartments" },
  { title: "Townhomes", category: "Townhomes" },
  { title: "Others", category: "Others" },
];

export const featuredProperties = [
  {
    id: "1",
    name: "Modern Villa",
    address: "Beverly Hills, CA",
    price: "2,500,000",
    rating: "4.8",
    image: "@/assets/images/japan.png",
    category: "Villa",
  },
  {
    id: "2",
    name: "Luxury Penthouse",
    address: "Miami Beach, FL",
    price: "3,200,000",
    rating: "4.9",
    image: "@/assets/images/japan.png",
    category: "Apartments",
  },
  {
    id: "3",
    name: "Beachfront Estate",
    address: "Malibu, CA",
    price: "5,800,000",
    rating: "5.0",
    image: "@/assets/images/japan.png",
    category: "House",
  },
];

export const properties = [
  {
    id: "4",
    name: "Luxury Apartment",
    address: "Manhattan, New York",
    price: "1,200,000",
    rating: "4.5",
    image: "@/assets/images/new-york.png",
    category: "Apartments",
  },
  {
    id: "5",
    name: "Modern Condo",
    address: "Downtown LA",
    price: "850,000",
    rating: "4.3",
    image: "@/assets/images/new-york.png",
    category: "Condos",
  },
  {
    id: "6",
    name: "Family House",
    address: "Austin, Texas",
    price: "680,000",
    rating: "4.6",
    image: "@/assets/images/new-york.png",
    category: "House",
  },
  {
    id: "7",
    name: "Studio Loft",
    address: "Brooklyn, NY",
    price: "520,000",
    rating: "4.2",
    image: "@/assets/images/new-york.png",
    category: "Studios",
  },
  {
    id: "8",
    name: "Suburban Duplex",
    address: "Seattle, WA",
    price: "750,000",
    rating: "4.4",
    image: "@/assets/images/new-york.png",
    category: "Duplexes",
  },
  {
    id: "9",
    name: "Elegant Townhome",
    address: "Boston, MA",
    price: "920,000",
    rating: "4.7",
    image: "@/assets/images/new-york.png",
    category: "Townhomes",
  },
];

export const facilities = [
  { title: "Parking", icon: "car-outline" },
  { title: "Swimming Pool", icon: "water-outline" },
  { title: "Gym", icon: "fitness-outline" },
  { title: "Garden", icon: "leaf-outline" },
  { title: "Security", icon: "shield-checkmark-outline" },
  { title: "Wifi", icon: "wifi-outline" },
  { title: "Elevator", icon: "arrow-up-outline" },
  { title: "Balcony", icon: "home-outline" },
  { title: "Laundry", icon: "shirt-outline" },
  { title: "Pet Friendly", icon: "paw-outline" },
];
